accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^signup/$', views.register, name='signup'),
]

ecollege/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from .import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^students/', include('student.urls')),
    url(r'^forums/', include('forums.urls')),
    url(r'^courses/', include('course.urls')),
    url(r'^tutors/', include('tutor.urls')),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^success-registration/$', views.success_reg, name='success_reg'),
    url(r'^login_redirect/$', views.login_redirect, name='login_redirect'),
    url(r'^students-update/$', views.student_sign_up, name='student_sign_up'),
    url(r'^tutors-update/$', views.tutor_sign_up, name='tutor_sign_up'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutor/urls.py
from django.conf.urls import url
from .import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/dashboard/$', views.tutor_dashboard, name='dashboard_list'),
    url(r'^(?P<pk>\d+)/student-list/$', views.tutor_student_list, name='tutor_student_list'),
    url(r'^all-tutors/$', views.tutor_list, name='tutors_all'),
    url(r'^(?P<pk>\d+)/courses/$', views.tutor_course_list, name='tutor_course'),
    url(r'^courses/create-courses/$', views.tutor_create_course, name='tutor_create'),
    url(r'^(?P<pk>\d+)/courses/(?P<slug>[\w-]+)/edit-course/$',
        views.TutorCourseUpdateView.as_view(), name='tutor_edit'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/add-topic/$', views.TutorCreateTopicView.as_view(),  name='tutor_create_topic'),
    url(r'^(?P<pk>\d+)/topic/$', views.tutor_course_topics,  name='tutor_course_topics'),
    url(r'^(?P<pk>\d+)/(?P<topic_title>[\w-]+)/topic/update$',
        views.TutorTopicUpdateView.as_view(),  name='topic_update'),
    url(r'^(?P<pk>\d+)/courses/delete-course/$', views.tutor_delete_course, name='tutor_delete'),
    url(r'^(?P<tutor_user>\w+)/(?P<pk>\d+)/profile$', views.tutor_profile, name='profile'),
    url(r'^(?P<tutor_user>\w+)/(?P<pk>\d+)/profile/edit-profile/$', views.tutor_update, name='profile_edit'),
]

accounts/models.py
from django.contrib.auth.models import User
from accounts.forms import forms
from student.models import Student
from tutor.models import Tutor


class UserForm(forms.ModelForm):
        class Meta:
                model = User
                fields = ["username", "first_name", "last_name", "email", "is_staff", "is_active", "password"]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm


class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password')


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'is_active', 'is_staff', 'username', 'password1', 'password2')

accounts/views.py
from django.contrib import auth, messages

from django.contrib.auth import login, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from accounts.forms import SignUpForm


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('success_reg')
    else:
        form = SignUpForm()
    return render(request, 'accounts/register.html', {'form': form})


def logout(request):
    auth.logout(request)
    return redirect('/')

templates/accounts/login.html
{% extends 'layouts/master.html' %}
{% load staticfiles %}
{% block title %}
Login
{% endblock %}
{% block content %}
    <body class="login">
    <div id="content" style="margin-left: 20%">
        <form method="post">
             {% csrf_token %}
            <div class="container-fluid">
            <div class="lock-container">
                <div class="panel panel-default text-center paper-shadow" data-z="0.5">
                    <h1 class="text-display-1 text-center margin-bottom-none">Sign In</h1>
                    {% if messages %}
            <ul>
                {% for message in messages %}
                <p class="text-center" style="color: red;margin-right: 15%;">{{ message }}</p>
                {% endfor %}
            </ul>
        {% endif %}
                                        <div class="panel-body">
                        <div class="form-group">
                            <div class="form-control-material">
                                <input class="form-control" id="id_username" name="username" required="" type="text" placeholder="Username">
                                <label for="username">Username</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-control-material">
                                <input class="form-control" id="id_password" name="password" type="password" required="" placeholder="Enter Password">
                                <label for="password">Password</label>
                            </div>
                        </div>
                        <button class="btn btn-primary">Login <i class="fa fa-fw fa-unlock-alt"></i></button>
                        <a href="#" class="forgot-password">Forgot password?</a>
                        <a href="{% url 'signup' %}" class="link-text-color">Create account</a>
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>
    </body>
{% endblock %}

templates/accounts/logout.html
{% extends 'layouts/master.html'  %}
{% load staticfiles %}
{% block title %}
  Logout
{% endblock %}

{% block content %}

    <div class="content">
        <div class="st-container">

        <p>You are logged out. <a href="{% url 'login' %}">Click here</a> to login again.</p>

        </div>
    </div>

{% endblock %}

templates/accounts/register.html
{% extends 'layouts/master.html' %}
{% load staticfiles %}
{% block title %}
Register
{% endblock %}
{% block content %}
 <body class="login">
    <div id="content" style="margin-left: 20%; top: 0%;">
        <div class="container-fluid">
            <div class="lock-container" style="top: 0%;">
                <div class="panel panel-default text-center paper-shadow" data-z="0.5" style="top: 0%;">
                    <h1 class="text-display-1">Create account</h1>
                    <div class="panel-body">
                      <form method="post">
                        {% csrf_token %}
                          {% include 'includes/form.html' %}
                        <button type="submit" class="btn btn-primary">Register</button>
                           <br><br> <br><br>
                      </form>
            </div>
        </div>
            </div>
        </div>
    </div>
   </body>
{% endblock %}

templates/accounts/signup.html
{% extends 'layouts/master.html' %}
{% load staticfiles %}
{% block title %}
Register
{% endblock %}
{% block content %}

    <div class="container" style="margin-left: 50%">
    <body class="login">
    <div id="content">
            <div class="lock-container">
                <div class="panel panel-default text-center paper-shadow" data-z="0.5">
                    <h1 class="text-display-1">Create account</h1>
                    <div class="panel-body">
                        <!-- Signup -->
                        <form role="form" action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="form-control-material">
                                    <input id="firstName" type="text" class="form-control" placeholder="First Name">
                                    <label for="firstName">First name</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-control-material">
                                    <label for="id_username">Username:</label><br>
                               <input type="text" name="username" required maxlength="150" autofocus id="id_username" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-control-material">
                                    <label for="id_first_name">First name:</label><br>
                            <input type="text" name="first_name" maxlength="30" id="id_first_name" />
                                </div>
                            </div>
                                <div class="form-group">
                                <div class="form-control-material">
                                     <label for="id_last_name">Last name:</label><br>
                            <input type="text" name="last_name" maxlength="30" id="id_last_name" />
                                </div>
                            </div>
                                <div class="form-group">
                                <div class="form-control-material">
                                    <label for="id_email">Email:</label><br>
                            <input type="email" name="email" required maxlength="200" id="id_email" />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="form-control-material">
                                    <label for="id_is_staff">Staff status:</label><br>
                            <input type="checkbox" name="is_staff" id="id_is_staff" />
                                </div>
                            </div>
                                <div class="form-group">
                                <div class="form-control-material">
                                    <label for="id_is_active">Active:</label><br>
                            <input type="checkbox" name="is_active" checked id="id_is_active" />
                                </div>
                            </div>
                                <div class="form-group">
                                <div class="form-control-material">
                                   <label for="id_password1">Password:</label><br>
                            <input type="password" name="password1" required id="id_password1" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-control-material">
                                     <label for="id_password2">Password confirmation:</label><br>
                            <input type="password" name="password2" required id="id_password2" />
                                </div>
                            </div>
                            <div class="form-group text-center">
                                <div class="checkbox">
                                    <input type="checkbox" id="agree" />
                                    <label for="agree">* I Agree with <a href="#">Terms &amp; Conditions!</a></label>
                                </div>
                            </div>
                            <div class="text-center">
                                <button>Create an Account</button>>
                            </div>
                        </form>

                        <!-- //Signup -->
                    </div>
                </div>
            </div>
        </div>
     </body>
    </div>
    <style>
    input{
        border: none;
  border-radius: 0;
  border-bottom: 1px solid #efefef;
  position: relative;
  box-shadow: none;
  padding: 16px 0 0;
  height: 48px;
    }
    </style>
{% endblock %}