ecollege/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from .import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^students/', include('student.urls')),
    url(r'^forums/', include('forums.urls')),
    url(r'^courses/', include('course.urls')),
    url(r'^tutors/', include('tutor.urls')),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^success-registration/$', views.success_reg, name='success_reg'),
    url(r'^login_redirect/$', views.login_redirect, name='login_redirect'),
    url(r'^students-update/$', views.student_sign_up, name='student_sign_up'),
    url(r'^tutors-update/$', views.tutor_sign_up, name='tutor_sign_up'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutor/urls.py
from django.conf.urls import url
from .import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/dashboard/$', views.tutor_dashboard, name='dashboard_list'),
    url(r'^(?P<pk>\d+)/student-list/$', views.tutor_student_list, name='tutor_student_list'),
    url(r'^all-tutors/$', views.tutor_list, name='tutors_all'),
    url(r'^(?P<pk>\d+)/courses/$', views.tutor_course_list, name='tutor_course'),
    url(r'^courses/create-courses/$', views.tutor_create_course, name='tutor_create'),
    url(r'^(?P<pk>\d+)/courses/(?P<slug>[\w-]+)/edit-course/$',
        views.TutorCourseUpdateView.as_view(), name='tutor_edit'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/add-topic/$', views.TutorCreateTopicView.as_view(),  name='tutor_create_topic'),
    url(r'^(?P<pk>\d+)/topic/$', views.tutor_course_topics,  name='tutor_course_topics'),
    url(r'^(?P<pk>\d+)/(?P<topic_title>[\w-]+)/topic/update$',
        views.TutorTopicUpdateView.as_view(),  name='topic_update'),
    url(r'^(?P<pk>\d+)/courses/delete-course/$', views.tutor_delete_course, name='tutor_delete'),
    url(r'^(?P<tutor_user>\w+)/(?P<pk>\d+)/profile$', views.tutor_profile, name='profile'),
    url(r'^(?P<tutor_user>\w+)/(?P<pk>\d+)/profile/edit-profile/$', views.tutor_update, name='profile_edit'),
]

course/models.py
from django.db import models
from django.urls import reverse

from tutor.models import Tutor


class CourseCategory(models.Model):
    course_type = models.CharField(max_length=200)
    course_level = models.CharField(max_length=255, choices=(('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')))

    class Meta:
        verbose_name_plural = 'Course Category'

    def __str__(self):
        return '{} {}'.format(self.course_type, self.course_level)


class Course(models.Model):
    category = models.ManyToManyField(CourseCategory, related_name='course_category')
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='course')
    blob = models.CharField(max_length=500)
    description = models.TextField()
    tutor = models.ManyToManyField(Tutor)
    created = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Course'

    def __str__(self):
        return self.title


class Topic(models.Model):
    topics_course = models.ForeignKey(Course)
    topic_chapter = models.PositiveIntegerField()
    topic_title = models.CharField(max_length=200)
    topic_slug = models.SlugField(max_length=200, default=True)
    topic_description = models.TextField()
    topic_duration = models.CharField(max_length=10)

    class Meta:
        verbose_name_plural = 'Topic'

    def __str__(self):
        return self.topic_title

    def get_absolute_url(self):
        return reverse('tutor_course_topics', kwargs={'pk': self.topics_course.pk})

student/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.http import request

from course.models import Course


class Student(models.Model):
    STUDENT = 1
    TUTOR = 2
    ADMIN = 3
    ROLE_CHOICES = (
        (STUDENT, 'Student'),
        (TUTOR, 'Tutor'),
        (ADMIN, 'Admin'),
    )
    student_user = models.OneToOneField(User, related_name='student')
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length=20, choices=(('Male', 'Male'), ('Female', 'Female')))
    picture = models.ImageField(upload_to='student')
    address = models.CharField(max_length=500)
    state = models.CharField(max_length=200)
    country = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Student'

    def __str__(self):
        return self.student_user.username


class StudentCourses(models.Model):
    student = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    student_course = models.ManyToManyField(Course)

    class Meta:
        verbose_name_plural = 'Student Courses'

tutor/models.py
from django.contrib.auth.models import User
from django.db import models


class Tutor(models.Model):
    STUDENT = 1
    TUTOR = 2
    ADMIN = 3
    ROLE_CHOICES = (
        (STUDENT, 'Student'),
        (TUTOR, 'Tutor'),
        (ADMIN, 'Admin'),
    )
    tutor_user = models.OneToOneField(User, related_name='tutor')
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)
    photo = models.ImageField(upload_to='tutor', null=True, blank=True)
    designation = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    address = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=200, null=True, blank=True)
    country = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Tutor'

    def __str__(self):
        return self.tutor_user.username

tutor/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import ModelForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect, get_list_or_404
from django.urls import reverse
from django.views.generic import UpdateView, CreateView

from tutor.models import Tutor
from course.models import Course, Topic
from student.models import StudentCourses, Student


class TutorCourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ['category', 'title', 'slug', 'image', 'blob', 'description', 'tutor']


@login_required
def tutor_dashboard(request, pk):
    tutor = get_object_or_404(Tutor, tutor_user=request.user)
    course = Course.objects.filter(tutor__tutor_user=request.user)
    student = StudentCourses.objects.filter(student__tutor__course=True)
    context = {'tutor': tutor, 'course': course, 'student': student}
    return render(request, 'tutor/tutor_board.html', context)


@login_required
def tutor_course_list(request, pk):
    tutor = get_object_or_404(Tutor, tutor_user=request.user)
    course = Course.objects.filter(tutor__tutor_user=request.user)
    context = {'tutor': tutor, 'course': course}
    return render(request, 'tutor/tutor_course.html', context)


@login_required
def tutor_create_course(request):
    tutor = get_object_or_404(Tutor, tutor_user=request.user)
    form = TutorCourseForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('tutor_course',)
    return render(request, 'tutor/create.html', {'form': form, 'tutor': tutor})


class TutorCourseUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'tutor/edit.html'
    model = Course
    fields = ['title', 'slug', 'image', 'blob', 'description', 'tutor']

    def get_context_data(self, **kwargs):
        context = super(TutorCourseUpdateView, self).get_context_data(**kwargs)
        context['course'] = Course.objects.filter(category=self.object.pk)
        context['tutor'] = get_object_or_404(Tutor, tutor_user=self.request.user)
        context['topic'] = Topic.objects.filter(topics_course=self.object)
        return context

    def form_valid(self, form):
            form.instance.course = self.request.user
            return super(TutorCourseUpdateView, self).form_valid(form)

    def get_success_url(self):
            return reverse('tutor_course', kwargs={'pk': self.object.pk})


@login_required
def tutor_delete_course(request, pk):
    course = get_object_or_404(Course, pk=pk)
    tutor = get_object_or_404(Tutor, tutor_user=request.user)
    form = TutorCourseForm(request.POST or None, instance=course)
    if request.method == 'POST':
        course.delete()
        return redirect('tutor_course', pk)
    return render(request, 'tutor/tutor_confirm_delete.html', {'form': form, 'course': course, 'tutor': tutor})


@login_required
def tutor_list(request):
    our_list = Tutor.objects.all()
    log_tutor = get_object_or_404(Tutor, tutor_user=request.user)
    context = {
        'our_list': our_list,
        'log_tutor': log_tutor
    }
    return render(request, 'tutor/tutor_list.html', context)


class TutorDataForm(ModelForm):
    class Meta:
        model = Tutor
        fields = ['phone', 'website', 'bio', 'address', 'state', 'country']


@login_required
def tutor_profile(request, pk, tutor_user):
    if request.user.is_authenticated:
        tutor = get_object_or_404(Tutor, tutor_user=request.user)
        return render(request, 'tutor/profile.html', {'tutor': tutor})


@login_required
def tutor_update(request, pk, tutor_user):
    tutor = get_object_or_404(Tutor, pk=pk, tutor_user=request.user)
    form = TutorDataForm(request.POST or None, instance=tutor)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('profile', tutor_user, pk)
    return render(request, 'tutor/edit.html', {'form': form, 'tutor': tutor})


@login_required
def tutor_student_list(request, pk):
    tutor = get_object_or_404(Tutor, pk=pk, tutor_user=request.user)
    list_student = Student.objects.all().order_by('id')
    return render(request, 'tutor/student_list.html', {'list_student': list_student, 'tutor': tutor})


def tutor_course_topics(request, pk):
    if request.user.is_staff and request.user.is_authenticated():
        course = Course.objects.get(id=pk)
        tutor = get_object_or_404(Tutor, tutor_user=request.user)
        topic = Topic.objects.filter(topics_course=course).order_by('id')
        return render(request, 'tutor/topic_course.html', {'course': course, 'topic': topic, 'tutor': tutor})


class TutorCreateTopicView(LoginRequiredMixin, CreateView):
    model = Topic
    template_name = 'tutor/topic.html'
    fields = ['topics_course', 'topic_chapter', 'topic_title',  'topic_slug', 'topic_description', 'topic_duration']

    def get_context_data(self,  **kwargs):
        context = super(TutorCreateTopicView, self).get_context_data(**kwargs)
        context['tutor'] = get_object_or_404(Tutor, tutor_user=self.request.user)
        return context

    def form_valid(self, form):
            form.fields.topics_course = self.object
            return super(TutorCreateTopicView, self).form_valid(form)


class TutorTopicUpdateView(LoginRequiredMixin, UpdateView):
    model = Topic
    fields = ['topic_chapter', 'topic_title',  'topic_slug',  'topic_description', 'topic_duration']
    template_name = 'tutor/topic_form.html'

    def get_context_data(self, **kwargs):
        context = super(TutorTopicUpdateView, self).get_context_data(**kwargs)
        context['tutor'] = get_object_or_404(Tutor, tutor_user=self.request.user)
        return context

templates/tutor/create.html
{% extends 'layouts/master.html' %}
{% load staticfiles %}
{% block title %}
Create Course
{% endblock %}
{% block content %}
    {% include 'layouts/tutor_navbar.html' %}

<div class="st-content-inner padding-none" style="margin-left: 20%">
<h3 class="text-left">Create Course</h3>
  <table class="table table-striped">
      <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <li class="list-group-item">{{ form.as_table }}</li>
          <tr>
              <td><button>Create</button></td>
          </tr>

      </form>
  </table>

</div>

{% endblock %}

templates/tutor/edit.html
{% extends 'layouts/master.html' %}
{% load staticfiles %}
{% block title %}
{{ tutor.tutor_user }}'s Profile Edit
{% endblock %}
{% block content %}
    {% include 'layouts/tutor_navbar.html' %}

<div class="st-content-inner padding-none" style="margin-left: 20%">
<h3 class="text-left">Update Course</h3>
  <table class="table table-striped">

      <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% include 'includes/form.html' %}
          <tr>
              <td><button>Update</button></td>
          </tr>

      </form>
  </table>

</div>

{% endblock %}

templates/tutor/student_list.html
{% extends 'layouts/master.html' %}
{% load staticfiles %}
{% block title %}
Student List
{% endblock %}
{% block content %}
    {% include 'layouts/tutor_navbar.html' %}
    <br><br>
{% if request.user.is_authenticated and request.user.is_active %}
            <div class="st-content" style="margin-left: 20%;">
                <!-- extra div for emulating position:fixed of the menu -->
                <div class="st-content-inner padding-none">
                    <div class="container-fluid">
                        <div class="page-section third">
                             <table class="table table-striped table-responsive">
                                 <tr>
                                     <th>S/No</th>
                                     <th>First Name</th>
                                     <th>Last Name</th>
                                     <th>Gender</th>
                                     <th>Age</th>
                                     <th>No of Courses Registered</th>
                                 </tr>


                                 {% for l in list_student %}
                                 <tr>
                                         <td>{{ l.id }}</td>
                                         <td><a href="#">{{ l.student_user.first_name }}</a></td>
                                         <td>{{ l.student_user.last_name }}</td>
                                         <td>{{ l.gender }}</td>
                                         <td>{{ l.age }}</td>
                                         <td>{{ l.student_user.studentcourses_set.count }}</td>
                                 </tr>
                                  {% endfor %}
                             </table>
                        <p class="text-center" style="background: grey; color:#fff">
                            No. Of Students: {{ list_student.count }}
                        </p>



                        </div>
                    </div>


                </div>
            </div>
{% endif %}
{% endblock %}

templates/tutor/topic.html
{% extends 'layouts/master.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block title %}
Create {{ course.title }} Topic
{% endblock %}
{% block content %}
    {% include 'layouts/tutor_navbar.html' %}

<div class="st-content-inner padding-none" style="margin-left: 20%">
<h3 class="text-left">Add Topic(s) to {{course.title}}</h3>
    <div class="col-md-8">
  <table class="table table-striped">

      <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
{#          {% include 'includes/form.html' %}#}
          {{ form|crispy }}
          <tr>
              <td><button>Save</button></td>
          </tr>

      </form>
  </table>
    </div>

</div>

{% endblock %}

templates/tutor/topic_form.html
{% extends 'layouts/master.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block title %}
Edit {{ topic.title }}
{% endblock %}
{% block content %}
    {% include 'layouts/tutor_navbar.html' %}
<br>
<div class="st-content-inner padding-none" style="margin-left: 20%">
<div class="col-md-8">
  <table class="table table-striped">

      <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
{#          {% include 'includes/form.html' %}#}
          {{ form|crispy }}
          <tr>
              <td><button>Update</button></td>
          </tr>

      </form>
  </table>
</div>

</div>

{% endblock %}

templates/tutor/tutor_confirm_delete.html
{% extends 'layouts/master.html' %}
{% load staticfiles %}
{% block title %}
Delete Course
{% endblock %}
{% block content %}
    {% include 'layouts/tutor_navbar.html' %}
 <div class="st-content" style="margin-left: 20%">
   <div class="st-content-inner padding-none">
                <!-- extra div for emulating position:fixed of the menu -->
                <div class="st-content-inner padding-none">
                    <div class="container-fluid">
                        <div class="page-section">
                            <h3 class="text-display-1"  style="margin-left: 15%">You want to delete  {{ course.title }}?</h3>
    <div class="row" data-toggle="isotope">
                            <div class="item col-xs-12 col-lg-8"  style="margin-left: 15%">
                                <div class="panel panel-default" data-z="0.5">
                                    <div class="panel-heading">
                                        <div class="media v-middle">
                                            <div class="media-body">
                                            {% csrf_token %}
                                                <h4 class="text-info text-center">
                                                    Are you sure you want to delete "{{ course.title }}" ?
                                                </h4>
                                                <button class="btn btn-danger">
                                                    Delete
                                                </button>
                                            </form>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
    </div>
                        </div>
                    </div>
                </div>
   </div>
 </div>
{% endblock %}

templates/tutor/tutor_form.html
{% extends 'layouts/master.html' %}
{% load staticfiles %}
{% block title %}
Edit Profile
{% endblock %}
{% block content %}
    {% include 'layouts/tutor_navbar.html' %}

<div class="st-content-inner padding-none" style="margin-left: 20%">
{% if request.user.is_authenticated %}
<h3 class="text-left">Update Profile</h3>
  <table class="table table-striped">
      <form action="" method="post">
          {% csrf_token %}
          {% include 'includes/form.html' %}
          <tr>
              <td><button>Update</button></td>
          </tr>

      </form>
  </table>
{% else %}
<h4 class="text-info">You cannot access this tutor's edit profile</h4>
{% endif %}

</div>

{% endblock %}

templates/tutor/tutor_list.html
{% extends 'layouts/master.html' %}
{% load staticfiles %}
{% block title %}
Tutors
{% endblock %}
{% block content %}
<div class="navbar navbar-default navbar-fixed-top navbar-size-large navbar-size-xlarge paper-shadow" data-z="0" data-animated role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand navbar-brand-logo">
<h3 class="text-left">eCollege</h3>
                </div>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="main-nav">
                <ul class="nav navbar-nav navbar-nav-margin-left">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'course_listing' %}">Course List</a></li>
                            <li><a href="website-course.html">Single Course</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Student <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="website-student-dashboard.html">Dashboard</a></li>
                            <li><a href="website-student-courses.html">My Courses</a></li>
                            <li><a href="website-take-course.html">Take Course</a></li>
                            <li><a href="website-course-forums.html">Course Forums</a></li>
                            <li><a href="website-take-quiz.html">Take Quiz</a></li>
                            <li><a href="website-student-messages.html">Messages</a></li>
                            <li><a href="website-student-profile.html">Private Profile</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Instructor <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="website-instructor-dashboard.html">Dashboard</a></li>
                            <li><a href="website-instructor-courses.html">My Courses</a></li>
                            <li><a href="website-instructor-course-edit-course.html">Edit Course</a></li>
                            <li><a href="website-instructor-earnings.html">Earnings</a></li>
                            <li><a href="website-instructor-statement.html">Statement</a></li>
                            <li><a href="website-instructor-messages.html">Messages</a></li>
                            <li><a href="website-instructor-profile.html">Private Profile</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="navbar-right">
                    <ul class="nav navbar-nav navbar-nav-bordered navbar-nav-margin-right">
                        <!-- user -->
                        <li class="dropdown user">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{ log_tutor.photo.url }}" alt="" class="img-circle" />
                                {{ log_tutor.tutor_user.first_name }}<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'dashboard_list' log_tutor.pk %}"><i class="fa fa-bar-chart-o"></i> Dashboard</a></li>
                                <li><a href="{% url 'tutor_course' log_tutor.pk %}"><i class="fa fa-mortar-board"></i> My Courses</a></li>
                                <li><a href="website-student-profile.html"><i class="fa fa-user"></i> Profile</a></li>
                                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Logout</a></li>
                            </ul>
                        </li>
                        <!-- // END user -->
                    </ul>
                </div>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </div>
    <div class="parallax cover overlay height-300 height-500-lg height-320-xs">
        <img class="parallax-layer"
             src="{% static 'images/photodune-6745579-modern-creative-man-relaxing-on-workspace-m.jpg' %}" alt="parallax image" />
        <div class="parallax-layer overlay overlay-full" data-opacity="true">
            <div class="v-center">
                <div class="container">
                    <h1 class="text-display-1 overlay-bg-white-strong display-inline-block">Learn from the best Tutors</h1>
                    <p class="text-subhead overlay-bg-white-strong"><span>{% lorem %}</span></p>
                </div>
            </div>
        </div>
    </div>
     <div class="page-section">
        <div class="container">

            <div class="row" data-toggle="isotope">
                {% for pro in our_list %}
                <div class="item col-xs-12 col-sm-6 col-lg-4">
                    <div class="panel panel-default paper-shadow" data-z="0.5">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="#">
                                {{ pro.tutor_user.first_name}} {{ pro.tutor_user.last_name}}
                            </a></h3>
                        </div>
                        <div class="panel-body">
                            <div class="media">
                                <div class="media-left">
                                    <a href="#">
                                        <img src="{{ pro.photo.url }}" height="50"
                                             width="50" class="img-circle" alt="people" />
                                    </a>
                                </div>
                                <div class="media-body">
                                    <p>{{ pro.bio }}</p>
                                    <span class="label label-default">{{ pro.designation }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <h5 class="margin-none">Latest course</h5>
                            <div class="media">
                                <div class="media-left">
                                    <a href="#" class="icon-block half bg-gray-dark"><i class="text-white fa fa-html5"></i></a>
                                </div>
                                <div class="media-body">
                                    <h4 class="media-heading"><a href="#" class="text-primary">
                                        {{ pro.course_set.last }}
                                    </a></h4>
                                    <p class="small text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero odit quas qui quo repellat? Commodi ex harum ipsam ullam. Harum!</p>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer text-right">
                            <a href="{% url 'profile' pro.tutor_user pro.pk %}" class="btn btn-sm btn-primary">View profile</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
     <section class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <h4 class="text-headline text-light">Corporate</h4>
                    <ul class="list-unstyled">
                        <li><a href="#">About the company</a></li>
                        <li><a href="#">Company offices</a></li>
                        <li><a href="#">Partners</a></li>
                        <li><a href="#">Terms of use</a></li>
                        <li><a href="#">Privacy</a></li>
                        <li><a href="#">Contact us</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3">
                    <h4 class="text-headline text-light">Explore</h4>
                    <ul class="list-unstyled">
                        <li><a href="">Courses</a></li>
                        <li><a href="">Tutors</a></li>
                        <li><a href="">Pricing</a></li>
                        <li><a href="">Become Tutor</a></li>
                        <li><a href="">Sign Up</a></li>
                    </ul>
                </div>
                <div class="col-xs-12 col-md-6">
                    <h4 class="text-headline text-light">Newsletter</h4>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Enter email here...">
                            <span class="input-group-btn">
								<button class="btn btn-grey-800" type="button">Subscribe</button>
							  </span>
                        </div>
                    </div>
                    <br/>
                    <p>
                        <a href="#" class="btn btn-indigo-500 btn-circle"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="btn btn-pink-500 btn-circle"><i class="fa fa-dribbble"></i></a>
                        <a href="#" class="btn btn-blue-500 btn-circle"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="btn btn-danger btn-circle"><i class="fa fa-google-plus"></i></a>
                    </p>
                    <p class="text-subhead">
                        &copy; {% now 'Y' %} Learning App by Sebig Solutions Limited.
                    </p>
                </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}